###################################################################

# Created by write_sdc on Wed May  6 15:31:58 2020

###################################################################
set sdc_version 1.9

set_units -time ns -resistance kOhm -capacitance pF -power mW -voltage V       \
-current mA
set_operating_conditions -max V105WTP1250 -max_library std150e_wst_105_p125\
                         -min V135BTN0400 -min_library std150e_bst_135_n040
set_max_fanout 6 [current_design]
set_max_area 0
set_disable_timing [get_ports i_RSTN]
set_load -pin_load 0.01035 [get_ports o_X_DATA_READY]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[31]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[30]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[29]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[28]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[27]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[26]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[25]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[24]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[23]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[22]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[21]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[20]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[19]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[18]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[17]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[16]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[15]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[14]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[13]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[12]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[11]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[10]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[9]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[8]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[7]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[6]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[5]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[4]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[3]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[2]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[1]}]
set_load -pin_load 0.01035 [get_ports {o_Y_DATA[0]}]
set_load -pin_load 0.01035 [get_ports o_Y_DATA_VALID]
set_load -pin_load 0 [get_ports i_CLK]
set_ideal_network [get_ports i_RSTN]
create_clock [get_ports i_CLK]  -name clk  -period 20  -waveform {0 10}
set_clock_latency 1.5  [get_clocks clk]
set_clock_uncertainty -setup 0.15  [get_clocks clk]
set_clock_transition -max -rise 0.5 [get_clocks clk]
set_clock_transition -max -fall 0.5 [get_clocks clk]
set_input_delay -clock clk  -max 1.2  [get_ports i_CLK]
set_input_delay -clock clk  -max 1.2  [get_ports i_RSTN]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[31]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[30]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[29]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[28]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[27]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[26]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[25]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[24]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[23]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[22]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[21]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[20]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[19]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[18]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[17]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[16]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[15]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[14]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[13]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[12]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[11]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[10]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[9]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[8]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[7]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[6]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[5]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[4]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[3]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[2]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[1]}]
set_input_delay -clock clk  -max 1.2  [get_ports {i_X_DATA[0]}]
set_input_delay -clock clk  -max 1.2  [get_ports i_X_DATA_VALID]
set_input_delay -clock clk  -max 1.2  [get_ports i_Y_ACK]
set_output_delay -clock clk  -max 1.5  [get_ports o_X_DATA_READY]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[31]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[30]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[29]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[28]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[27]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[26]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[25]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[24]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[23]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[22]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[21]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[20]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[19]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[18]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[17]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[16]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[15]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[14]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[13]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[12]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[11]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[10]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[9]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[8]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[7]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[6]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[5]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[4]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[3]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[2]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[1]}]
set_output_delay -clock clk  -max 1.5  [get_ports {o_Y_DATA[0]}]
set_output_delay -clock clk  -max 1.5  [get_ports o_Y_DATA_VALID]
set_input_transition -max 0.5  [get_ports {i_X_DATA[31]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[30]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[29]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[28]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[27]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[26]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[25]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[24]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[23]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[22]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[21]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[20]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[19]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[18]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[17]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[16]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[15]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[14]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[13]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[12]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[11]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[10]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[9]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[8]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[7]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[6]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[5]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[4]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[3]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[2]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[1]}]
set_input_transition -max 0.5  [get_ports {i_X_DATA[0]}]
set_input_transition -max 0.5  [get_ports i_X_DATA_VALID]
set_input_transition -max 0.5  [get_ports i_Y_ACK]
set_input_transition -max 0.5  [get_ports i_CLK]
set_input_transition -max 0.5  [get_ports i_RSTN]
