setq mylib (dbOpenLib "std150e_prim")
dbCreateCellLEQClass mylib "ad2bd1_hd" "ad2bd2_hd"
dbCreateCellLEQClass mylib "ad2bd1_hd" "ad2bd4_hd"
dbCreateCellLEQClass mylib "ad2bd1_hd" "ad2bd6_hd"
dbCreateCellLEQClass mylib "ad2bd1_hd" "ad2bd8_hd"
dbCreateCellLEQClass mylib "ad2bd1_hd" "ad2bdh_hd"

dbCreateCellLEQClass mylib "ad2d1_hd" "ad2d2_hd"
dbCreateCellLEQClass mylib "ad2d1_hd" "ad2d4_hd"
dbCreateCellLEQClass mylib "ad2d1_hd" "ad2d6_hd"
dbCreateCellLEQClass mylib "ad2d1_hd" "ad2d8_hd"
dbCreateCellLEQClass mylib "ad2d1_hd" "ad2dh_hd"

dbCreateCellLEQClass mylib "ad3d1_hd" "ad3d2_hd"
dbCreateCellLEQClass mylib "ad3d1_hd" "ad3d4_hd"
dbCreateCellLEQClass mylib "ad3d1_hd" "ad3d6_hd"
dbCreateCellLEQClass mylib "ad3d1_hd" "ad3d8_hd"
dbCreateCellLEQClass mylib "ad3d1_hd" "ad3dh_hd"

dbCreateCellLEQClass mylib "ad4d1_hd" "ad4d2_hd"
dbCreateCellLEQClass mylib "ad4d1_hd" "ad4d4_hd"
dbCreateCellLEQClass mylib "ad4d1_hd" "ad4d6_hd"
dbCreateCellLEQClass mylib "ad4d1_hd" "ad4d8_hd"
dbCreateCellLEQClass mylib "ad4d1_hd" "ad4dh_hd"

dbCreateCellLEQClass mylib "ao211d1_hd" "ao211d2_hd"
dbCreateCellLEQClass mylib "ao211d1_hd" "ao211d4_hd"
dbCreateCellLEQClass mylib "ao211d1_hd" "ao211d8_hd"
dbCreateCellLEQClass mylib "ao211d1_hd" "ao211dh_hd"

dbCreateCellLEQClass mylib "ao21d1_hd" "ao21d2_hd"
dbCreateCellLEQClass mylib "ao21d1_hd" "ao21d4_hd"
dbCreateCellLEQClass mylib "ao21d1_hd" "ao21d8_hd"
dbCreateCellLEQClass mylib "ao21d1_hd" "ao21dh_hd"

dbCreateCellLEQClass mylib "ao221d1_hd" "ao221d2_hd"
dbCreateCellLEQClass mylib "ao221d1_hd" "ao221d4_hd"
dbCreateCellLEQClass mylib "ao221d1_hd" "ao221d8_hd"
dbCreateCellLEQClass mylib "ao221d1_hd" "ao221dh_hd"

dbCreateCellLEQClass mylib "ao222ad1_hd" "ao222ad2_hd"
dbCreateCellLEQClass mylib "ao222ad1_hd" "ao222ad4_hd"
dbCreateCellLEQClass mylib "ao222ad1_hd" "ao222ad8_hd"
dbCreateCellLEQClass mylib "ao222ad1_hd" "ao222adh_hd"

dbCreateCellLEQClass mylib "ao222d1_hd" "ao222d2_hd"
dbCreateCellLEQClass mylib "ao222d1_hd" "ao222d4_hd"
dbCreateCellLEQClass mylib "ao222d1_hd" "ao222d8_hd"
dbCreateCellLEQClass mylib "ao222d1_hd" "ao222dh_hd"

dbCreateCellLEQClass mylib "ao22ad1_hd" "ao22ad2_hd"
dbCreateCellLEQClass mylib "ao22ad1_hd" "ao22ad4_hd"
dbCreateCellLEQClass mylib "ao22ad1_hd" "ao22ad8_hd"
dbCreateCellLEQClass mylib "ao22ad1_hd" "ao22adh_hd"

dbCreateCellLEQClass mylib "ao22d1_hd" "ao22d2_hd"
dbCreateCellLEQClass mylib "ao22d1_hd" "ao22d4_hd"
dbCreateCellLEQClass mylib "ao22d1_hd" "ao22d8_hd"
dbCreateCellLEQClass mylib "ao22d1_hd" "ao22dh_hd"

dbCreateCellLEQClass mylib "ao31d1_hd" "ao31d2_hd"
dbCreateCellLEQClass mylib "ao31d1_hd" "ao31d4_hd"
dbCreateCellLEQClass mylib "ao31d1_hd" "ao31d8_hd"
dbCreateCellLEQClass mylib "ao31d1_hd" "ao31dh_hd"

dbCreateCellLEQClass mylib "ao32d1_hd" "ao32d2_hd"
dbCreateCellLEQClass mylib "ao32d1_hd" "ao32d4_hd"
dbCreateCellLEQClass mylib "ao32d1_hd" "ao32d8_hd"
dbCreateCellLEQClass mylib "ao32d1_hd" "ao32dh_hd"

dbCreateCellLEQClass mylib "ao33d1_hd" "ao33d2_hd"
dbCreateCellLEQClass mylib "ao33d1_hd" "ao33d4_hd"
dbCreateCellLEQClass mylib "ao33d1_hd" "ao33d8_hd"
dbCreateCellLEQClass mylib "ao33d1_hd" "ao33dh_hd"

dbCreateCellLEQClass mylib "cglnd1_hd" "cglnd12_hd"
dbCreateCellLEQClass mylib "cglnd1_hd" "cglnd16_hd"
dbCreateCellLEQClass mylib "cglnd1_hd" "cglnd20_hd"
dbCreateCellLEQClass mylib "cglnd1_hd" "cglnd24_hd"
dbCreateCellLEQClass mylib "cglnd1_hd" "cglnd2_hd"
dbCreateCellLEQClass mylib "cglnd1_hd" "cglnd32_hd"
dbCreateCellLEQClass mylib "cglnd1_hd" "cglnd3_hd"
dbCreateCellLEQClass mylib "cglnd1_hd" "cglnd4_hd"
dbCreateCellLEQClass mylib "cglnd1_hd" "cglnd6_hd"
dbCreateCellLEQClass mylib "cglnd1_hd" "cglnd8_hd"

dbCreateCellLEQClass mylib "cglpd1_hd" "cglpd12_hd"
dbCreateCellLEQClass mylib "cglpd1_hd" "cglpd16_hd"
dbCreateCellLEQClass mylib "cglpd1_hd" "cglpd20_hd"
dbCreateCellLEQClass mylib "cglpd1_hd" "cglpd24_hd"
dbCreateCellLEQClass mylib "cglpd1_hd" "cglpd2_hd"
dbCreateCellLEQClass mylib "cglpd1_hd" "cglpd32_hd"
dbCreateCellLEQClass mylib "cglpd1_hd" "cglpd3_hd"
dbCreateCellLEQClass mylib "cglpd1_hd" "cglpd4_hd"
dbCreateCellLEQClass mylib "cglpd1_hd" "cglpd6_hd"
dbCreateCellLEQClass mylib "cglpd1_hd" "cglpd8_hd"

dbCreateCellLEQClass mylib "clkad2d1_hd" "clkad2d2_hd"
dbCreateCellLEQClass mylib "clkad2d1_hd" "clkad2d3_hd"
dbCreateCellLEQClass mylib "clkad2d1_hd" "clkad2d4_hd"
dbCreateCellLEQClass mylib "clkad2d1_hd" "clkad2d6_hd"
dbCreateCellLEQClass mylib "clkad2d1_hd" "clkad2d8_hd"

dbCreateCellLEQClass mylib "clkivd1_hd" "clkivd12_hd"
dbCreateCellLEQClass mylib "clkivd1_hd" "clkivd16_hd"
dbCreateCellLEQClass mylib "clkivd1_hd" "clkivd20_hd"
dbCreateCellLEQClass mylib "clkivd1_hd" "clkivd24_hd"
dbCreateCellLEQClass mylib "clkivd1_hd" "clkivd2_hd"
dbCreateCellLEQClass mylib "clkivd1_hd" "clkivd32_hd"
dbCreateCellLEQClass mylib "clkivd1_hd" "clkivd3_hd"
dbCreateCellLEQClass mylib "clkivd1_hd" "clkivd40_hd"
dbCreateCellLEQClass mylib "clkivd1_hd" "clkivd48_hd"
dbCreateCellLEQClass mylib "clkivd1_hd" "clkivd4_hd"
dbCreateCellLEQClass mylib "clkivd1_hd" "clkivd6_hd"
dbCreateCellLEQClass mylib "clkivd1_hd" "clkivd8_hd"

dbCreateCellLEQClass mylib "clkmx2d1_hd" "clkmx2d12_hd"
dbCreateCellLEQClass mylib "clkmx2d1_hd" "clkmx2d16_hd"
dbCreateCellLEQClass mylib "clkmx2d1_hd" "clkmx2d2_hd"
dbCreateCellLEQClass mylib "clkmx2d1_hd" "clkmx2d3_hd"
dbCreateCellLEQClass mylib "clkmx2d1_hd" "clkmx2d4_hd"
dbCreateCellLEQClass mylib "clkmx2d1_hd" "clkmx2d6_hd"
dbCreateCellLEQClass mylib "clkmx2d1_hd" "clkmx2d8_hd"

dbCreateCellLEQClass mylib "clknd2d1_hd" "clknd2d2_hd"
dbCreateCellLEQClass mylib "clknd2d1_hd" "clknd2d3_hd"
dbCreateCellLEQClass mylib "clknd2d1_hd" "clknd2d4_hd"
dbCreateCellLEQClass mylib "clknd2d1_hd" "clknd2d6_hd"
dbCreateCellLEQClass mylib "clknd2d1_hd" "clknd2d8_hd"

dbCreateCellLEQClass mylib "clknid1_hd" "clknid12_hd"
dbCreateCellLEQClass mylib "clknid1_hd" "clknid16_hd"
dbCreateCellLEQClass mylib "clknid1_hd" "clknid20_hd"
dbCreateCellLEQClass mylib "clknid1_hd" "clknid24_hd"
dbCreateCellLEQClass mylib "clknid1_hd" "clknid2_hd"
dbCreateCellLEQClass mylib "clknid1_hd" "clknid32_hd"
dbCreateCellLEQClass mylib "clknid1_hd" "clknid3_hd"
dbCreateCellLEQClass mylib "clknid1_hd" "clknid40_hd"
dbCreateCellLEQClass mylib "clknid1_hd" "clknid48_hd"
dbCreateCellLEQClass mylib "clknid1_hd" "clknid4_hd"
dbCreateCellLEQClass mylib "clknid1_hd" "clknid6_hd"
dbCreateCellLEQClass mylib "clknid1_hd" "clknid8_hd"

dbCreateCellLEQClass mylib "clkxo2d1_hd" "clkxo2d2_hd"
dbCreateCellLEQClass mylib "clkxo2d1_hd" "clkxo2d3_hd"
dbCreateCellLEQClass mylib "clkxo2d1_hd" "clkxo2d4_hd"
dbCreateCellLEQClass mylib "clkxo2d1_hd" "clkxo2d6_hd"
dbCreateCellLEQClass mylib "clkxo2d1_hd" "clkxo2d8_hd"

dbCreateCellLEQClass mylib "fad1_hd" "fad2_hd"
dbCreateCellLEQClass mylib "fad1_hd" "fad4_hd"
dbCreateCellLEQClass mylib "fad1_hd" "fad8_hd"
dbCreateCellLEQClass mylib "fad1_hd" "fadh_hd"

dbCreateCellLEQClass mylib "fd1d1_hd" "fd1d2_hd"
dbCreateCellLEQClass mylib "fd1d1_hd" "fd1d4_hd"
dbCreateCellLEQClass mylib "fd1d1_hd" "fd1dh_hd"

dbCreateCellLEQClass mylib "fd1ed1_hd" "fd1ed2_hd"
dbCreateCellLEQClass mylib "fd1ed1_hd" "fd1ed4_hd"
dbCreateCellLEQClass mylib "fd1ed1_hd" "fd1edh_hd"

dbCreateCellLEQClass mylib "fd1eqd1_hd" "fd1eqd2_hd"
dbCreateCellLEQClass mylib "fd1eqd1_hd" "fd1eqd4_hd"
dbCreateCellLEQClass mylib "fd1eqd1_hd" "fd1eqdh_hd"

dbCreateCellLEQClass mylib "fd1esd1_hd" "fd1esd2_hd"
dbCreateCellLEQClass mylib "fd1esd1_hd" "fd1esd4_hd"
dbCreateCellLEQClass mylib "fd1esd1_hd" "fd1esdh_hd"

dbCreateCellLEQClass mylib "fd1esqd1_hd" "fd1esqd2_hd"
dbCreateCellLEQClass mylib "fd1esqd1_hd" "fd1esqd4_hd"
dbCreateCellLEQClass mylib "fd1esqd1_hd" "fd1esqdh_hd"

dbCreateCellLEQClass mylib "fd1mqd1_hd" "fd1mqd2_hd"
dbCreateCellLEQClass mylib "fd1mqd1_hd" "fd1mqd4_hd"
dbCreateCellLEQClass mylib "fd1mqd1_hd" "fd1mqdh_hd"

dbCreateCellLEQClass mylib "fd1msqd1_hd" "fd1msqd2_hd"
dbCreateCellLEQClass mylib "fd1msqd1_hd" "fd1msqd4_hd"
dbCreateCellLEQClass mylib "fd1msqd1_hd" "fd1msqdh_hd"

dbCreateCellLEQClass mylib "fd1qd1_hd" "fd1qd2_hd"
dbCreateCellLEQClass mylib "fd1qd1_hd" "fd1qd4_hd"
dbCreateCellLEQClass mylib "fd1qd1_hd" "fd1qdh_hd"

dbCreateCellLEQClass mylib "fd1sd1_hd" "fd1sd2_hd"
dbCreateCellLEQClass mylib "fd1sd1_hd" "fd1sd4_hd"
dbCreateCellLEQClass mylib "fd1sd1_hd" "fd1sdh_hd"

dbCreateCellLEQClass mylib "fd1sqd1_hd" "fd1sqd2_hd"
dbCreateCellLEQClass mylib "fd1sqd1_hd" "fd1sqd4_hd"
dbCreateCellLEQClass mylib "fd1sqd1_hd" "fd1sqdh_hd"

dbCreateCellLEQClass mylib "fd2d1_hd" "fd2d2_hd"
dbCreateCellLEQClass mylib "fd2d1_hd" "fd2d4_hd"
dbCreateCellLEQClass mylib "fd2d1_hd" "fd2dh_hd"

dbCreateCellLEQClass mylib "fd2qd1_hd" "fd2qd2_hd"
dbCreateCellLEQClass mylib "fd2qd1_hd" "fd2qd4_hd"
dbCreateCellLEQClass mylib "fd2qd1_hd" "fd2qdh_hd"

dbCreateCellLEQClass mylib "fd2sd1_hd" "fd2sd2_hd"
dbCreateCellLEQClass mylib "fd2sd1_hd" "fd2sd4_hd"
dbCreateCellLEQClass mylib "fd2sd1_hd" "fd2sdh_hd"

dbCreateCellLEQClass mylib "fd2sqd1_hd" "fd2sqd2_hd"
dbCreateCellLEQClass mylib "fd2sqd1_hd" "fd2sqd4_hd"
dbCreateCellLEQClass mylib "fd2sqd1_hd" "fd2sqdh_hd"

dbCreateCellLEQClass mylib "fd3d1_hd" "fd3d2_hd"
dbCreateCellLEQClass mylib "fd3d1_hd" "fd3d4_hd"
dbCreateCellLEQClass mylib "fd3d1_hd" "fd3dh_hd"

dbCreateCellLEQClass mylib "fd3qd1_hd" "fd3qd2_hd"
dbCreateCellLEQClass mylib "fd3qd1_hd" "fd3qd4_hd"
dbCreateCellLEQClass mylib "fd3qd1_hd" "fd3qdh_hd"

dbCreateCellLEQClass mylib "fd3sd1_hd" "fd3sd2_hd"
dbCreateCellLEQClass mylib "fd3sd1_hd" "fd3sd4_hd"
dbCreateCellLEQClass mylib "fd3sd1_hd" "fd3sdh_hd"

dbCreateCellLEQClass mylib "fd3sqd1_hd" "fd3sqd2_hd"
dbCreateCellLEQClass mylib "fd3sqd1_hd" "fd3sqd4_hd"
dbCreateCellLEQClass mylib "fd3sqd1_hd" "fd3sqdh_hd"

dbCreateCellLEQClass mylib "fd4d1_hd" "fd4d2_hd"
dbCreateCellLEQClass mylib "fd4d1_hd" "fd4d4_hd"
dbCreateCellLEQClass mylib "fd4d1_hd" "fd4dh_hd"

dbCreateCellLEQClass mylib "fd4qd1_hd" "fd4qd2_hd"
dbCreateCellLEQClass mylib "fd4qd1_hd" "fd4qd4_hd"
dbCreateCellLEQClass mylib "fd4qd1_hd" "fd4qdh_hd"

dbCreateCellLEQClass mylib "fd4sd1_hd" "fd4sd2_hd"
dbCreateCellLEQClass mylib "fd4sd1_hd" "fd4sd4_hd"
dbCreateCellLEQClass mylib "fd4sd1_hd" "fd4sdh_hd"

dbCreateCellLEQClass mylib "fd4sqd1_hd" "fd4sqd2_hd"
dbCreateCellLEQClass mylib "fd4sqd1_hd" "fd4sqd4_hd"
dbCreateCellLEQClass mylib "fd4sqd1_hd" "fd4sqdh_hd"

dbCreateCellLEQClass mylib "fd5d1_hd" "fd5d2_hd"
dbCreateCellLEQClass mylib "fd5d1_hd" "fd5d4_hd"
dbCreateCellLEQClass mylib "fd5d1_hd" "fd5dh_hd"

dbCreateCellLEQClass mylib "fd5sd1_hd" "fd5sd2_hd"
dbCreateCellLEQClass mylib "fd5sd1_hd" "fd5sd4_hd"
dbCreateCellLEQClass mylib "fd5sd1_hd" "fd5sdh_hd"

dbCreateCellLEQClass mylib "fd6d1_hd" "fd6d2_hd"
dbCreateCellLEQClass mylib "fd6d1_hd" "fd6d4_hd"
dbCreateCellLEQClass mylib "fd6d1_hd" "fd6dh_hd"

dbCreateCellLEQClass mylib "fd6sd1_hd" "fd6sd2_hd"
dbCreateCellLEQClass mylib "fd6sd1_hd" "fd6sd4_hd"
dbCreateCellLEQClass mylib "fd6sd1_hd" "fd6sdh_hd"

dbCreateCellLEQClass mylib "fd7d1_hd" "fd7d2_hd"
dbCreateCellLEQClass mylib "fd7d1_hd" "fd7d4_hd"
dbCreateCellLEQClass mylib "fd7d1_hd" "fd7dh_hd"

dbCreateCellLEQClass mylib "fd7sd1_hd" "fd7sd2_hd"
dbCreateCellLEQClass mylib "fd7sd1_hd" "fd7sd4_hd"
dbCreateCellLEQClass mylib "fd7sd1_hd" "fd7sdh_hd"

dbCreateCellLEQClass mylib "fd8d1_hd" "fd8d2_hd"
dbCreateCellLEQClass mylib "fd8d1_hd" "fd8d4_hd"
dbCreateCellLEQClass mylib "fd8d1_hd" "fd8dh_hd"

dbCreateCellLEQClass mylib "fd8sd1_hd" "fd8sd2_hd"
dbCreateCellLEQClass mylib "fd8sd1_hd" "fd8sd4_hd"
dbCreateCellLEQClass mylib "fd8sd1_hd" "fd8sdh_hd"

dbCreateCellLEQClass mylib "fds2d1_hd" "fds2d2_hd"
dbCreateCellLEQClass mylib "fds2d1_hd" "fds2d4_hd"
dbCreateCellLEQClass mylib "fds2d1_hd" "fds2dh_hd"

dbCreateCellLEQClass mylib "fds2ed1_hd" "fds2ed2_hd"
dbCreateCellLEQClass mylib "fds2ed1_hd" "fds2ed4_hd"
dbCreateCellLEQClass mylib "fds2ed1_hd" "fds2edh_hd"

dbCreateCellLEQClass mylib "fds2eqd1_hd" "fds2eqd2_hd"
dbCreateCellLEQClass mylib "fds2eqd1_hd" "fds2eqd4_hd"
dbCreateCellLEQClass mylib "fds2eqd1_hd" "fds2eqdh_hd"

dbCreateCellLEQClass mylib "fds2esd1_hd" "fds2esd2_hd"
dbCreateCellLEQClass mylib "fds2esd1_hd" "fds2esd4_hd"
dbCreateCellLEQClass mylib "fds2esd1_hd" "fds2esdh_hd"

dbCreateCellLEQClass mylib "fds2esqd1_hd" "fds2esqd2_hd"
dbCreateCellLEQClass mylib "fds2esqd1_hd" "fds2esqd4_hd"
dbCreateCellLEQClass mylib "fds2esqd1_hd" "fds2esqdh_hd"

dbCreateCellLEQClass mylib "fds2sd1_hd" "fds2sd2_hd"
dbCreateCellLEQClass mylib "fds2sd1_hd" "fds2sd4_hd"
dbCreateCellLEQClass mylib "fds2sd1_hd" "fds2sdh_hd"

dbCreateCellLEQClass mylib "fds3d1_hd" "fds3d2_hd"
dbCreateCellLEQClass mylib "fds3d1_hd" "fds3d4_hd"
dbCreateCellLEQClass mylib "fds3d1_hd" "fds3dh_hd"

dbCreateCellLEQClass mylib "fds3sd1_hd" "fds3sd2_hd"
dbCreateCellLEQClass mylib "fds3sd1_hd" "fds3sd4_hd"
dbCreateCellLEQClass mylib "fds3sd1_hd" "fds3sdh_hd"

dbCreateCellLEQClass mylib "fj2d1_hd" "fj2d2_hd"
dbCreateCellLEQClass mylib "fj2d1_hd" "fj2d4_hd"
dbCreateCellLEQClass mylib "fj2d1_hd" "fj2dh_hd"

dbCreateCellLEQClass mylib "fj2sd1_hd" "fj2sd2_hd"
dbCreateCellLEQClass mylib "fj2sd1_hd" "fj2sd4_hd"
dbCreateCellLEQClass mylib "fj2sd1_hd" "fj2sdh_hd"

dbCreateCellLEQClass mylib "fj4d1_hd" "fj4d2_hd"
dbCreateCellLEQClass mylib "fj4d1_hd" "fj4d4_hd"
dbCreateCellLEQClass mylib "fj4d1_hd" "fj4dh_hd"

dbCreateCellLEQClass mylib "fj4sd1_hd" "fj4sd2_hd"
dbCreateCellLEQClass mylib "fj4sd1_hd" "fj4sd4_hd"
dbCreateCellLEQClass mylib "fj4sd1_hd" "fj4sdh_hd"

dbCreateCellLEQClass mylib "ft2d1_hd" "ft2d2_hd"
dbCreateCellLEQClass mylib "ft2d1_hd" "ft2d4_hd"
dbCreateCellLEQClass mylib "ft2d1_hd" "ft2dh_hd"

dbCreateCellLEQClass mylib "had1_hd" "had2_hd"
dbCreateCellLEQClass mylib "had1_hd" "had4_hd"
dbCreateCellLEQClass mylib "had1_hd" "had8_hd"
dbCreateCellLEQClass mylib "had1_hd" "hadh_hd"

dbCreateCellLEQClass mylib "holdbuf1d1_hd" "holdbuf1d2_hd"
dbCreateCellLEQClass mylib "holdbuf1d1_hd" "holdbuf1d4_hd"
dbCreateCellLEQClass mylib "holdbuf1d1_hd" "holdbuf2d1_hd"
dbCreateCellLEQClass mylib "holdbuf1d1_hd" "holdbuf2d2_hd"
dbCreateCellLEQClass mylib "holdbuf1d1_hd" "holdbuf2d4_hd"
dbCreateCellLEQClass mylib "holdbuf1d1_hd" "holdbuf3d1_hd"
dbCreateCellLEQClass mylib "holdbuf1d1_hd" "holdbuf3d2_hd"
dbCreateCellLEQClass mylib "holdbuf1d1_hd" "holdbuf3d4_hd"
dbCreateCellLEQClass mylib "holdbuf1d1_hd" "holdbuf4d1_hd"
dbCreateCellLEQClass mylib "holdbuf1d1_hd" "holdbuf4d2_hd"
dbCreateCellLEQClass mylib "holdbuf1d1_hd" "holdbuf4d4_hd"

dbCreateCellLEQClass mylib "holdbufad1_hd" "holdbufad2_hd"
dbCreateCellLEQClass mylib "holdbufad1_hd" "holdbufad4_hd"
dbCreateCellLEQClass mylib "holdbufad1_hd" "holdbufbd1_hd"
dbCreateCellLEQClass mylib "holdbufad1_hd" "holdbufbd2_hd"
dbCreateCellLEQClass mylib "holdbufad1_hd" "holdbufbd4_hd"
dbCreateCellLEQClass mylib "holdbufad1_hd" "holdbufcd1_hd"
dbCreateCellLEQClass mylib "holdbufad1_hd" "holdbufcd2_hd"
dbCreateCellLEQClass mylib "holdbufad1_hd" "holdbufcd4_hd"
dbCreateCellLEQClass mylib "holdbufad1_hd" "holdbufdd1_hd"
dbCreateCellLEQClass mylib "holdbufad1_hd" "holdbufdd2_hd"
dbCreateCellLEQClass mylib "holdbufad1_hd" "holdbufdd4_hd"

dbCreateCellLEQClass mylib "ivd1_hd" "ivd12_hd"
dbCreateCellLEQClass mylib "ivd1_hd" "ivd16_hd"
dbCreateCellLEQClass mylib "ivd1_hd" "ivd20_hd"
dbCreateCellLEQClass mylib "ivd1_hd" "ivd24_hd"
dbCreateCellLEQClass mylib "ivd1_hd" "ivd2_hd"
dbCreateCellLEQClass mylib "ivd1_hd" "ivd3_hd"
dbCreateCellLEQClass mylib "ivd1_hd" "ivd4_hd"
dbCreateCellLEQClass mylib "ivd1_hd" "ivd6_hd"
dbCreateCellLEQClass mylib "ivd1_hd" "ivd8_hd"
dbCreateCellLEQClass mylib "ivd1_hd" "ivdh_hd"

dbCreateCellLEQClass mylib "ivtd1_hd" "ivtd12_hd"
dbCreateCellLEQClass mylib "ivtd1_hd" "ivtd16_hd"
dbCreateCellLEQClass mylib "ivtd1_hd" "ivtd20_hd"
dbCreateCellLEQClass mylib "ivtd1_hd" "ivtd24_hd"
dbCreateCellLEQClass mylib "ivtd1_hd" "ivtd2_hd"
dbCreateCellLEQClass mylib "ivtd1_hd" "ivtd3_hd"
dbCreateCellLEQClass mylib "ivtd1_hd" "ivtd4_hd"
dbCreateCellLEQClass mylib "ivtd1_hd" "ivtd6_hd"
dbCreateCellLEQClass mylib "ivtd1_hd" "ivtd8_hd"

dbCreateCellLEQClass mylib "ld1d1_hd" "ld1d2_hd"
dbCreateCellLEQClass mylib "ld1d1_hd" "ld1d4_hd"
dbCreateCellLEQClass mylib "ld1d1_hd" "ld1dh_hd"

dbCreateCellLEQClass mylib "ld1qd1_hd" "ld1qd2_hd"
dbCreateCellLEQClass mylib "ld1qd1_hd" "ld1qd4_hd"
dbCreateCellLEQClass mylib "ld1qd1_hd" "ld1qdh_hd"

dbCreateCellLEQClass mylib "ld2d1_hd" "ld2d2_hd"
dbCreateCellLEQClass mylib "ld2d1_hd" "ld2d4_hd"
dbCreateCellLEQClass mylib "ld2d1_hd" "ld2dh_hd"

dbCreateCellLEQClass mylib "ld2qd1_hd" "ld2qd2_hd"
dbCreateCellLEQClass mylib "ld2qd1_hd" "ld2qd4_hd"
dbCreateCellLEQClass mylib "ld2qd1_hd" "ld2qdh_hd"

dbCreateCellLEQClass mylib "ld3d1_hd" "ld3d2_hd"
dbCreateCellLEQClass mylib "ld3d1_hd" "ld3d4_hd"
dbCreateCellLEQClass mylib "ld3d1_hd" "ld3dh_hd"

dbCreateCellLEQClass mylib "ld4d1_hd" "ld4d2_hd"
dbCreateCellLEQClass mylib "ld4d1_hd" "ld4d4_hd"
dbCreateCellLEQClass mylib "ld4d1_hd" "ld4dh_hd"

dbCreateCellLEQClass mylib "ld5d1_hd" "ld5d2_hd"
dbCreateCellLEQClass mylib "ld5d1_hd" "ld5d4_hd"
dbCreateCellLEQClass mylib "ld5d1_hd" "ld5dh_hd"

dbCreateCellLEQClass mylib "ld5qd1_hd" "ld5qd2_hd"
dbCreateCellLEQClass mylib "ld5qd1_hd" "ld5qd4_hd"
dbCreateCellLEQClass mylib "ld5qd1_hd" "ld5qdh_hd"

dbCreateCellLEQClass mylib "ld6d1_hd" "ld6d2_hd"
dbCreateCellLEQClass mylib "ld6d1_hd" "ld6d4_hd"
dbCreateCellLEQClass mylib "ld6d1_hd" "ld6dh_hd"

dbCreateCellLEQClass mylib "ld6qd1_hd" "ld6qd2_hd"
dbCreateCellLEQClass mylib "ld6qd1_hd" "ld6qd4_hd"
dbCreateCellLEQClass mylib "ld6qd1_hd" "ld6qdh_hd"

dbCreateCellLEQClass mylib "mx2d1_hd" "mx2d2_hd"
dbCreateCellLEQClass mylib "mx2d1_hd" "mx2d4_hd"
dbCreateCellLEQClass mylib "mx2d1_hd" "mx2d6_hd"
dbCreateCellLEQClass mylib "mx2d1_hd" "mx2d8_hd"
dbCreateCellLEQClass mylib "mx2d1_hd" "mx2dh_hd"

dbCreateCellLEQClass mylib "mx2id1_hd" "mx2id2_hd"
dbCreateCellLEQClass mylib "mx2id1_hd" "mx2id4_hd"
dbCreateCellLEQClass mylib "mx2id1_hd" "mx2id6_hd"
dbCreateCellLEQClass mylib "mx2id1_hd" "mx2id8_hd"
dbCreateCellLEQClass mylib "mx2id1_hd" "mx2idh_hd"

dbCreateCellLEQClass mylib "mx3d1_hd" "mx3d2_hd"
dbCreateCellLEQClass mylib "mx3d1_hd" "mx3d4_hd"
dbCreateCellLEQClass mylib "mx3d1_hd" "mx3d8_hd"
dbCreateCellLEQClass mylib "mx3d1_hd" "mx3dh_hd"

dbCreateCellLEQClass mylib "mx4d1_hd" "mx4d2_hd"
dbCreateCellLEQClass mylib "mx4d1_hd" "mx4d4_hd"
dbCreateCellLEQClass mylib "mx4d1_hd" "mx4d8_hd"
dbCreateCellLEQClass mylib "mx4d1_hd" "mx4dh_hd"

dbCreateCellLEQClass mylib "nd2bd1_hd" "nd2bd2_hd"
dbCreateCellLEQClass mylib "nd2bd1_hd" "nd2bd4_hd"
dbCreateCellLEQClass mylib "nd2bd1_hd" "nd2bd6_hd"
dbCreateCellLEQClass mylib "nd2bd1_hd" "nd2bd8_hd"
dbCreateCellLEQClass mylib "nd2bd1_hd" "nd2bdh_hd"

dbCreateCellLEQClass mylib "nd2d1_hd" "nd2d2_hd"
dbCreateCellLEQClass mylib "nd2d1_hd" "nd2d4_hd"
dbCreateCellLEQClass mylib "nd2d1_hd" "nd2d6_hd"
dbCreateCellLEQClass mylib "nd2d1_hd" "nd2d8_hd"
dbCreateCellLEQClass mylib "nd2d1_hd" "nd2dh_hd"

dbCreateCellLEQClass mylib "nd3bd1_hd" "nd3bd2_hd"
dbCreateCellLEQClass mylib "nd3bd1_hd" "nd3bd4_hd"
dbCreateCellLEQClass mylib "nd3bd1_hd" "nd3bd6_hd"
dbCreateCellLEQClass mylib "nd3bd1_hd" "nd3bd8_hd"
dbCreateCellLEQClass mylib "nd3bd1_hd" "nd3bdh_hd"

dbCreateCellLEQClass mylib "nd3d1_hd" "nd3d2_hd"
dbCreateCellLEQClass mylib "nd3d1_hd" "nd3d4_hd"
dbCreateCellLEQClass mylib "nd3d1_hd" "nd3d6_hd"
dbCreateCellLEQClass mylib "nd3d1_hd" "nd3d8_hd"
dbCreateCellLEQClass mylib "nd3d1_hd" "nd3dh_hd"

dbCreateCellLEQClass mylib "nd4d1_hd" "nd4d2_hd"
dbCreateCellLEQClass mylib "nd4d1_hd" "nd4d4_hd"
dbCreateCellLEQClass mylib "nd4d1_hd" "nd4d6_hd"
dbCreateCellLEQClass mylib "nd4d1_hd" "nd4d8_hd"
dbCreateCellLEQClass mylib "nd4d1_hd" "nd4dh_hd"

dbCreateCellLEQClass mylib "nid1_hd" "nid12_hd"
dbCreateCellLEQClass mylib "nid1_hd" "nid16_hd"
dbCreateCellLEQClass mylib "nid1_hd" "nid20_hd"
dbCreateCellLEQClass mylib "nid1_hd" "nid24_hd"
dbCreateCellLEQClass mylib "nid1_hd" "nid2_hd"
dbCreateCellLEQClass mylib "nid1_hd" "nid3_hd"
dbCreateCellLEQClass mylib "nid1_hd" "nid4_hd"
dbCreateCellLEQClass mylib "nid1_hd" "nid6_hd"
dbCreateCellLEQClass mylib "nid1_hd" "nid8_hd"
dbCreateCellLEQClass mylib "nid1_hd" "nidh_hd"

dbCreateCellLEQClass mylib "nitd1_hd" "nitd12_hd"
dbCreateCellLEQClass mylib "nitd1_hd" "nitd16_hd"
dbCreateCellLEQClass mylib "nitd1_hd" "nitd20_hd"
dbCreateCellLEQClass mylib "nitd1_hd" "nitd24_hd"
dbCreateCellLEQClass mylib "nitd1_hd" "nitd2_hd"
dbCreateCellLEQClass mylib "nitd1_hd" "nitd3_hd"
dbCreateCellLEQClass mylib "nitd1_hd" "nitd4_hd"
dbCreateCellLEQClass mylib "nitd1_hd" "nitd6_hd"
dbCreateCellLEQClass mylib "nitd1_hd" "nitd8_hd"

dbCreateCellLEQClass mylib "nr2bd1_hd" "nr2bd2_hd"
dbCreateCellLEQClass mylib "nr2bd1_hd" "nr2bd4_hd"
dbCreateCellLEQClass mylib "nr2bd1_hd" "nr2bd6_hd"
dbCreateCellLEQClass mylib "nr2bd1_hd" "nr2bd8_hd"
dbCreateCellLEQClass mylib "nr2bd1_hd" "nr2bdh_hd"

dbCreateCellLEQClass mylib "nr2d1_hd" "nr2ad1_hd"
dbCreateCellLEQClass mylib "nr2d1_hd" "nr2d2_hd"
dbCreateCellLEQClass mylib "nr2d1_hd" "nr2d4_hd"
dbCreateCellLEQClass mylib "nr2d1_hd" "nr2d6_hd"
dbCreateCellLEQClass mylib "nr2d1_hd" "nr2d8_hd"
dbCreateCellLEQClass mylib "nr2d1_hd" "nr2dh_hd"

dbCreateCellLEQClass mylib "nr3d1_hd" "nr3ad1_hd"
dbCreateCellLEQClass mylib "nr3d1_hd" "nr3d2_hd"
dbCreateCellLEQClass mylib "nr3d1_hd" "nr3d4_hd"
dbCreateCellLEQClass mylib "nr3d1_hd" "nr3d6_hd"
dbCreateCellLEQClass mylib "nr3d1_hd" "nr3d8_hd"
dbCreateCellLEQClass mylib "nr3d1_hd" "nr3dh_hd"

dbCreateCellLEQClass mylib "nr4d1_hd" "nr4d2_hd"
dbCreateCellLEQClass mylib "nr4d1_hd" "nr4d4_hd"
dbCreateCellLEQClass mylib "nr4d1_hd" "nr4d6_hd"
dbCreateCellLEQClass mylib "nr4d1_hd" "nr4d8_hd"
dbCreateCellLEQClass mylib "nr4d1_hd" "nr4dh_hd"

dbCreateCellLEQClass mylib "oa211d1_hd" "oa211d2_hd"
dbCreateCellLEQClass mylib "oa211d1_hd" "oa211d4_hd"
dbCreateCellLEQClass mylib "oa211d1_hd" "oa211d8_hd"
dbCreateCellLEQClass mylib "oa211d1_hd" "oa211dh_hd"

dbCreateCellLEQClass mylib "oa21d1_hd" "oa21d2_hd"
dbCreateCellLEQClass mylib "oa21d1_hd" "oa21d4_hd"
dbCreateCellLEQClass mylib "oa21d1_hd" "oa21d8_hd"
dbCreateCellLEQClass mylib "oa21d1_hd" "oa21dh_hd"

dbCreateCellLEQClass mylib "oa221d1_hd" "oa221d2_hd"
dbCreateCellLEQClass mylib "oa221d1_hd" "oa221d4_hd"
dbCreateCellLEQClass mylib "oa221d1_hd" "oa221d8_hd"
dbCreateCellLEQClass mylib "oa221d1_hd" "oa221dh_hd"

dbCreateCellLEQClass mylib "oa222d1_hd" "oa222d2_hd"
dbCreateCellLEQClass mylib "oa222d1_hd" "oa222d4_hd"
dbCreateCellLEQClass mylib "oa222d1_hd" "oa222d8_hd"
dbCreateCellLEQClass mylib "oa222d1_hd" "oa222dh_hd"

dbCreateCellLEQClass mylib "oa22ad1_hd" "oa22ad2_hd"
dbCreateCellLEQClass mylib "oa22ad1_hd" "oa22ad4_hd"
dbCreateCellLEQClass mylib "oa22ad1_hd" "oa22ad8_hd"
dbCreateCellLEQClass mylib "oa22ad1_hd" "oa22adh_hd"

dbCreateCellLEQClass mylib "oa22d1_hd" "oa22d2_hd"
dbCreateCellLEQClass mylib "oa22d1_hd" "oa22d4_hd"
dbCreateCellLEQClass mylib "oa22d1_hd" "oa22d8_hd"
dbCreateCellLEQClass mylib "oa22d1_hd" "oa22dh_hd"

dbCreateCellLEQClass mylib "oa31d1_hd" "oa31d2_hd"
dbCreateCellLEQClass mylib "oa31d1_hd" "oa31d4_hd"
dbCreateCellLEQClass mylib "oa31d1_hd" "oa31d8_hd"
dbCreateCellLEQClass mylib "oa31d1_hd" "oa31dh_hd"

dbCreateCellLEQClass mylib "oa32d1_hd" "oa32d2_hd"
dbCreateCellLEQClass mylib "oa32d1_hd" "oa32d4_hd"
dbCreateCellLEQClass mylib "oa32d1_hd" "oa32d8_hd"
dbCreateCellLEQClass mylib "oa32d1_hd" "oa32dh_hd"

dbCreateCellLEQClass mylib "oa33d1_hd" "oa33d2_hd"
dbCreateCellLEQClass mylib "oa33d1_hd" "oa33d4_hd"
dbCreateCellLEQClass mylib "oa33d1_hd" "oa33d8_hd"
dbCreateCellLEQClass mylib "oa33d1_hd" "oa33dh_hd"

dbCreateCellLEQClass mylib "or2bd1_hd" "or2bd2_hd"
dbCreateCellLEQClass mylib "or2bd1_hd" "or2bd4_hd"
dbCreateCellLEQClass mylib "or2bd1_hd" "or2bd6_hd"
dbCreateCellLEQClass mylib "or2bd1_hd" "or2bd8_hd"
dbCreateCellLEQClass mylib "or2bd1_hd" "or2bdh_hd"

dbCreateCellLEQClass mylib "or2d1_hd" "or2d2_hd"
dbCreateCellLEQClass mylib "or2d1_hd" "or2d4_hd"
dbCreateCellLEQClass mylib "or2d1_hd" "or2d6_hd"
dbCreateCellLEQClass mylib "or2d1_hd" "or2d8_hd"
dbCreateCellLEQClass mylib "or2d1_hd" "or2dh_hd"

dbCreateCellLEQClass mylib "or3d1_hd" "or3d2_hd"
dbCreateCellLEQClass mylib "or3d1_hd" "or3d4_hd"
dbCreateCellLEQClass mylib "or3d1_hd" "or3d6_hd"
dbCreateCellLEQClass mylib "or3d1_hd" "or3d8_hd"
dbCreateCellLEQClass mylib "or3d1_hd" "or3dh_hd"

dbCreateCellLEQClass mylib "or4d1_hd" "or4d2_hd"
dbCreateCellLEQClass mylib "or4d1_hd" "or4d4_hd"
dbCreateCellLEQClass mylib "or4d1_hd" "or4d6_hd"
dbCreateCellLEQClass mylib "or4d1_hd" "or4d8_hd"
dbCreateCellLEQClass mylib "or4d1_hd" "or4dh_hd"

dbCreateCellLEQClass mylib "scg10d1_hd" "scg10d2_hd"
dbCreateCellLEQClass mylib "scg10d1_hd" "scg10d4_hd"
dbCreateCellLEQClass mylib "scg10d1_hd" "scg10d8_hd"
dbCreateCellLEQClass mylib "scg10d1_hd" "scg10dh_hd"

dbCreateCellLEQClass mylib "scg11d1_hd" "scg11d2_hd"
dbCreateCellLEQClass mylib "scg11d1_hd" "scg11d4_hd"
dbCreateCellLEQClass mylib "scg11d1_hd" "scg11d8_hd"
dbCreateCellLEQClass mylib "scg11d1_hd" "scg11dh_hd"

dbCreateCellLEQClass mylib "scg12d1_hd" "scg12d2_hd"
dbCreateCellLEQClass mylib "scg12d1_hd" "scg12d4_hd"
dbCreateCellLEQClass mylib "scg12d1_hd" "scg12d8_hd"
dbCreateCellLEQClass mylib "scg12d1_hd" "scg12dh_hd"

dbCreateCellLEQClass mylib "scg13d1_hd" "scg13d2_hd"
dbCreateCellLEQClass mylib "scg13d1_hd" "scg13d4_hd"
dbCreateCellLEQClass mylib "scg13d1_hd" "scg13d8_hd"
dbCreateCellLEQClass mylib "scg13d1_hd" "scg13dh_hd"

dbCreateCellLEQClass mylib "scg14d1_hd" "scg14d2_hd"
dbCreateCellLEQClass mylib "scg14d1_hd" "scg14d4_hd"
dbCreateCellLEQClass mylib "scg14d1_hd" "scg14d8_hd"
dbCreateCellLEQClass mylib "scg14d1_hd" "scg14dh_hd"

dbCreateCellLEQClass mylib "scg15d1_hd" "scg15d2_hd"
dbCreateCellLEQClass mylib "scg15d1_hd" "scg15d4_hd"
dbCreateCellLEQClass mylib "scg15d1_hd" "scg15d8_hd"
dbCreateCellLEQClass mylib "scg15d1_hd" "scg15dh_hd"

dbCreateCellLEQClass mylib "scg16d1_hd" "scg16d2_hd"
dbCreateCellLEQClass mylib "scg16d1_hd" "scg16d4_hd"
dbCreateCellLEQClass mylib "scg16d1_hd" "scg16d8_hd"
dbCreateCellLEQClass mylib "scg16d1_hd" "scg16dh_hd"

dbCreateCellLEQClass mylib "scg17d1_hd" "scg17d2_hd"
dbCreateCellLEQClass mylib "scg17d1_hd" "scg17d4_hd"
dbCreateCellLEQClass mylib "scg17d1_hd" "scg17d8_hd"
dbCreateCellLEQClass mylib "scg17d1_hd" "scg17dh_hd"

dbCreateCellLEQClass mylib "scg18d1_hd" "scg18d2_hd"
dbCreateCellLEQClass mylib "scg18d1_hd" "scg18d4_hd"
dbCreateCellLEQClass mylib "scg18d1_hd" "scg18d8_hd"
dbCreateCellLEQClass mylib "scg18d1_hd" "scg18dh_hd"

dbCreateCellLEQClass mylib "scg1d1_hd" "scg1d2_hd"
dbCreateCellLEQClass mylib "scg1d1_hd" "scg1d4_hd"
dbCreateCellLEQClass mylib "scg1d1_hd" "scg1d8_hd"
dbCreateCellLEQClass mylib "scg1d1_hd" "scg1dh_hd"

dbCreateCellLEQClass mylib "scg20d1_hd" "scg20d2_hd"
dbCreateCellLEQClass mylib "scg20d1_hd" "scg20d4_hd"
dbCreateCellLEQClass mylib "scg20d1_hd" "scg20d8_hd"
dbCreateCellLEQClass mylib "scg20d1_hd" "scg20dh_hd"

dbCreateCellLEQClass mylib "scg21d1_hd" "scg21d2_hd"
dbCreateCellLEQClass mylib "scg21d1_hd" "scg21d4_hd"
dbCreateCellLEQClass mylib "scg21d1_hd" "scg21d8_hd"
dbCreateCellLEQClass mylib "scg21d1_hd" "scg21dh_hd"

dbCreateCellLEQClass mylib "scg22d1_hd" "scg22d2_hd"
dbCreateCellLEQClass mylib "scg22d1_hd" "scg22d4_hd"
dbCreateCellLEQClass mylib "scg22d1_hd" "scg22d8_hd"
dbCreateCellLEQClass mylib "scg22d1_hd" "scg22dh_hd"

dbCreateCellLEQClass mylib "scg2d1_hd" "scg2d2_hd"
dbCreateCellLEQClass mylib "scg2d1_hd" "scg2d4_hd"
dbCreateCellLEQClass mylib "scg2d1_hd" "scg2d8_hd"
dbCreateCellLEQClass mylib "scg2d1_hd" "scg2dh_hd"

dbCreateCellLEQClass mylib "scg3d1_hd" "scg3d2_hd"
dbCreateCellLEQClass mylib "scg3d1_hd" "scg3d4_hd"
dbCreateCellLEQClass mylib "scg3d1_hd" "scg3d8_hd"
dbCreateCellLEQClass mylib "scg3d1_hd" "scg3dh_hd"

dbCreateCellLEQClass mylib "scg4d1_hd" "scg4d2_hd"
dbCreateCellLEQClass mylib "scg4d1_hd" "scg4d4_hd"
dbCreateCellLEQClass mylib "scg4d1_hd" "scg4d8_hd"
dbCreateCellLEQClass mylib "scg4d1_hd" "scg4dh_hd"

dbCreateCellLEQClass mylib "scg5d1_hd" "scg5d2_hd"
dbCreateCellLEQClass mylib "scg5d1_hd" "scg5d4_hd"
dbCreateCellLEQClass mylib "scg5d1_hd" "scg5d8_hd"
dbCreateCellLEQClass mylib "scg5d1_hd" "scg5dh_hd"

dbCreateCellLEQClass mylib "scg6d1_hd" "scg6d2_hd"
dbCreateCellLEQClass mylib "scg6d1_hd" "scg6d4_hd"
dbCreateCellLEQClass mylib "scg6d1_hd" "scg6d8_hd"
dbCreateCellLEQClass mylib "scg6d1_hd" "scg6dh_hd"

dbCreateCellLEQClass mylib "scg7d1_hd" "scg7d2_hd"
dbCreateCellLEQClass mylib "scg7d1_hd" "scg7d4_hd"
dbCreateCellLEQClass mylib "scg7d1_hd" "scg7d8_hd"
dbCreateCellLEQClass mylib "scg7d1_hd" "scg7dh_hd"

dbCreateCellLEQClass mylib "scg8d1_hd" "scg8d2_hd"
dbCreateCellLEQClass mylib "scg8d1_hd" "scg8d4_hd"
dbCreateCellLEQClass mylib "scg8d1_hd" "scg8d8_hd"
dbCreateCellLEQClass mylib "scg8d1_hd" "scg8dh_hd"

dbCreateCellLEQClass mylib "scg9d1_hd" "scg9d2_hd"
dbCreateCellLEQClass mylib "scg9d1_hd" "scg9d4_hd"
dbCreateCellLEQClass mylib "scg9d1_hd" "scg9d8_hd"
dbCreateCellLEQClass mylib "scg9d1_hd" "scg9dh_hd"

dbCreateCellLEQClass mylib "xn2d1_hd" "xn2d2_hd"
dbCreateCellLEQClass mylib "xn2d1_hd" "xn2d4_hd"
dbCreateCellLEQClass mylib "xn2d1_hd" "xn2d8_hd"
dbCreateCellLEQClass mylib "xn2d1_hd" "xn2dh_hd"

dbCreateCellLEQClass mylib "xn3d1_hd" "xn3d2_hd"
dbCreateCellLEQClass mylib "xn3d1_hd" "xn3d4_hd"
dbCreateCellLEQClass mylib "xn3d1_hd" "xn3d8_hd"
dbCreateCellLEQClass mylib "xn3d1_hd" "xn3dh_hd"

dbCreateCellLEQClass mylib "xo2d1_hd" "xo2d2_hd"
dbCreateCellLEQClass mylib "xo2d1_hd" "xo2d4_hd"
dbCreateCellLEQClass mylib "xo2d1_hd" "xo2d8_hd"
dbCreateCellLEQClass mylib "xo2d1_hd" "xo2dh_hd"

dbCreateCellLEQClass mylib "xo3d1_hd" "xo3d2_hd"
dbCreateCellLEQClass mylib "xo3d1_hd" "xo3d4_hd"
dbCreateCellLEQClass mylib "xo3d1_hd" "xo3d8_hd"
dbCreateCellLEQClass mylib "xo3d1_hd" "xo3dh_hd"

