set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction horizontal  -start_at 1034.280 -nets VDD -layer MET3 -width 3.280 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1019.810 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 174.230 -nets VDD -layer MET3 -width 3.280 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1019.810 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 1018.170 -nets VDD -layer MET4 -width 3.280 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1035.920 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 170.710 -nets VDD -layer MET4 -width 3.280 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1035.920 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1030.560 -nets VSS -layer MET3 -width 3.280 -start_low_ends coordinate  -start_low_ends_coordinate 172.790 -start_high_ends coordinate  -start_high_ends_coordinate 1016.090 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 177.950 -nets VSS -layer MET3 -width 3.280 -start_low_ends coordinate  -start_low_ends_coordinate 172.790 -start_high_ends coordinate  -start_high_ends_coordinate 1016.090 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 1014.450 -nets VSS -layer MET4 -width 3.280 -start_low_ends coordinate  -start_low_ends_coordinate 176.310 -start_high_ends coordinate  -start_high_ends_coordinate 1032.200 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 174.430 -nets VSS -layer MET4 -width 3.280 -start_low_ends coordinate  -start_low_ends_coordinate 176.310 -start_high_ends coordinate  -start_high_ends_coordinate 1032.200 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal5 straps for net VDD
create_power_straps  -direction horizontal  -start_at 212.730 -nets VDD  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1019.810 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 246.730 -nets VDD  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1019.810 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 280.330 -nets VDD  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1019.810 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 314.330 -nets VDD  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1019.810 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 348.330 -nets VDD  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1019.810 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 382.330 -nets VDD  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1019.810 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 416.330 -nets VDD  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1019.810 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 450.330 -nets VDD  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1019.810 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 483.930 -nets VDD  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1019.810 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 517.930 -nets VDD  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1019.810 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 551.930 -nets VDD  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1019.810 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 585.930 -nets VDD  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1019.810 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 619.930 -nets VDD  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1019.810 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 653.930 -nets VDD  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1019.810 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 687.530 -nets VDD  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1019.810 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 721.530 -nets VDD  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1019.810 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 755.530 -nets VDD  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1019.810 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 789.530 -nets VDD  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1019.810 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 823.530 -nets VDD  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1019.810 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 857.530 -nets VDD  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1019.810 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 891.130 -nets VDD  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1019.810 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 925.130 -nets VDD  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1019.810 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 959.130 -nets VDD  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1019.810 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 993.130 -nets VDD  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1019.810 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal5 straps for net VSS
create_power_straps  -direction horizontal  -start_at 215.410 -nets VSS  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 172.790 -start_high_ends coordinate  -start_high_ends_coordinate 1016.090 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 249.410 -nets VSS  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 172.790 -start_high_ends coordinate  -start_high_ends_coordinate 1016.090 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 283.010 -nets VSS  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 172.790 -start_high_ends coordinate  -start_high_ends_coordinate 1016.090 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 317.010 -nets VSS  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 172.790 -start_high_ends coordinate  -start_high_ends_coordinate 1016.090 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 351.010 -nets VSS  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 172.790 -start_high_ends coordinate  -start_high_ends_coordinate 1016.090 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 385.010 -nets VSS  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 172.790 -start_high_ends coordinate  -start_high_ends_coordinate 1016.090 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 419.010 -nets VSS  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 172.790 -start_high_ends coordinate  -start_high_ends_coordinate 1016.090 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 453.010 -nets VSS  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 172.790 -start_high_ends coordinate  -start_high_ends_coordinate 1016.090 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 486.610 -nets VSS  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 172.790 -start_high_ends coordinate  -start_high_ends_coordinate 1016.090 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 520.610 -nets VSS  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 172.790 -start_high_ends coordinate  -start_high_ends_coordinate 1016.090 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 554.610 -nets VSS  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 172.790 -start_high_ends coordinate  -start_high_ends_coordinate 1016.090 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 588.610 -nets VSS  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 172.790 -start_high_ends coordinate  -start_high_ends_coordinate 1016.090 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 622.610 -nets VSS  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 172.790 -start_high_ends coordinate  -start_high_ends_coordinate 1016.090 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 656.610 -nets VSS  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 172.790 -start_high_ends coordinate  -start_high_ends_coordinate 1016.090 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 690.210 -nets VSS  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 172.790 -start_high_ends coordinate  -start_high_ends_coordinate 1016.090 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 724.210 -nets VSS  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 172.790 -start_high_ends coordinate  -start_high_ends_coordinate 1016.090 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 758.210 -nets VSS  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 172.790 -start_high_ends coordinate  -start_high_ends_coordinate 1016.090 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 792.210 -nets VSS  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 172.790 -start_high_ends coordinate  -start_high_ends_coordinate 1016.090 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 826.210 -nets VSS  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 172.790 -start_high_ends coordinate  -start_high_ends_coordinate 1016.090 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 860.210 -nets VSS  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 172.790 -start_high_ends coordinate  -start_high_ends_coordinate 1016.090 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 893.810 -nets VSS  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 172.790 -start_high_ends coordinate  -start_high_ends_coordinate 1016.090 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 927.810 -nets VSS  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 172.790 -start_high_ends coordinate  -start_high_ends_coordinate 1016.090 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 961.810 -nets VSS  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 172.790 -start_high_ends coordinate  -start_high_ends_coordinate 1016.090 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 995.810 -nets VSS  -layer MET5 -width 2.050 -pitch_within_group 33.930 -start_low_ends coordinate  -start_low_ends_coordinate 172.790 -start_high_ends coordinate  -start_high_ends_coordinate 1016.090 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal6 straps for net VDD
create_power_straps  -direction vertical  -start_at 208.480 -nets VDD  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1035.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 241.920 -nets VDD  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1035.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 275.360 -nets VDD  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1035.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 308.800 -nets VDD  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1035.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 342.240 -nets VDD  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1035.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 375.680 -nets VDD  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1035.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 409.120 -nets VDD  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1035.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 442.560 -nets VDD  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1035.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 476.000 -nets VDD  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1035.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 509.440 -nets VDD  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1035.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 542.880 -nets VDD  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1035.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 576.320 -nets VDD  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1035.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 609.760 -nets VDD  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1035.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 643.200 -nets VDD  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1035.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 676.640 -nets VDD  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1035.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 710.080 -nets VDD  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1035.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 743.520 -nets VDD  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1035.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 776.960 -nets VDD  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1035.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 810.400 -nets VDD  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1035.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 843.840 -nets VDD  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1035.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 877.280 -nets VDD  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1035.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 910.720 -nets VDD  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1035.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 944.160 -nets VDD  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1035.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 977.600 -nets VDD  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1035.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal6 straps for net VSS
create_power_straps  -direction vertical  -start_at 211.200 -nets VSS  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 176.310 -start_high_ends coordinate  -start_high_ends_coordinate 1032.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 244.640 -nets VSS  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 176.310 -start_high_ends coordinate  -start_high_ends_coordinate 1032.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 278.080 -nets VSS  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 176.310 -start_high_ends coordinate  -start_high_ends_coordinate 1032.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 311.520 -nets VSS  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 176.310 -start_high_ends coordinate  -start_high_ends_coordinate 1032.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 344.960 -nets VSS  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 176.310 -start_high_ends coordinate  -start_high_ends_coordinate 1032.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 378.400 -nets VSS  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 176.310 -start_high_ends coordinate  -start_high_ends_coordinate 1032.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 411.840 -nets VSS  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 176.310 -start_high_ends coordinate  -start_high_ends_coordinate 1032.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 445.280 -nets VSS  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 176.310 -start_high_ends coordinate  -start_high_ends_coordinate 1032.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 478.720 -nets VSS  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 176.310 -start_high_ends coordinate  -start_high_ends_coordinate 1032.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 512.160 -nets VSS  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 176.310 -start_high_ends coordinate  -start_high_ends_coordinate 1032.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 545.600 -nets VSS  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 176.310 -start_high_ends coordinate  -start_high_ends_coordinate 1032.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 579.040 -nets VSS  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 176.310 -start_high_ends coordinate  -start_high_ends_coordinate 1032.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 612.480 -nets VSS  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 176.310 -start_high_ends coordinate  -start_high_ends_coordinate 1032.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 645.920 -nets VSS  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 176.310 -start_high_ends coordinate  -start_high_ends_coordinate 1032.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 679.360 -nets VSS  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 176.310 -start_high_ends coordinate  -start_high_ends_coordinate 1032.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 712.800 -nets VSS  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 176.310 -start_high_ends coordinate  -start_high_ends_coordinate 1032.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 746.240 -nets VSS  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 176.310 -start_high_ends coordinate  -start_high_ends_coordinate 1032.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 779.680 -nets VSS  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 176.310 -start_high_ends coordinate  -start_high_ends_coordinate 1032.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 813.120 -nets VSS  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 176.310 -start_high_ends coordinate  -start_high_ends_coordinate 1032.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 846.560 -nets VSS  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 176.310 -start_high_ends coordinate  -start_high_ends_coordinate 1032.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 880.000 -nets VSS  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 176.310 -start_high_ends coordinate  -start_high_ends_coordinate 1032.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 913.440 -nets VSS  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 176.310 -start_high_ends coordinate  -start_high_ends_coordinate 1032.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 946.880 -nets VSS  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 176.310 -start_high_ends coordinate  -start_high_ends_coordinate 1032.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 980.320 -nets VSS  -layer MET6 -width 2.150 -pitch_within_group 33.430 -start_low_ends coordinate  -start_low_ends_coordinate 176.310 -start_high_ends coordinate  -start_high_ends_coordinate 1032.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
