set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction horizontal  -start_at 1227.800 -nets VDD -layer MET3 -width 1.240 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 173.210 -nets VDD -layer MET3 -width 1.240 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 1230.330 -nets VDD -layer MET4 -width 1.240 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 169.690 -nets VDD -layer MET4 -width 1.240 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1226.320 -nets VSS -layer MET3 -width 1.240 -start_low_ends coordinate  -start_low_ends_coordinate 170.550 -start_high_ends coordinate  -start_high_ends_coordinate 1229.470 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 174.690 -nets VSS -layer MET3 -width 1.240 -start_low_ends coordinate  -start_low_ends_coordinate 170.550 -start_high_ends coordinate  -start_high_ends_coordinate 1229.470 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 1228.850 -nets VSS -layer MET4 -width 1.240 -start_low_ends coordinate  -start_low_ends_coordinate 174.070 -start_high_ends coordinate  -start_high_ends_coordinate 1226.940 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 171.170 -nets VSS -layer MET4 -width 1.240 -start_low_ends coordinate  -start_low_ends_coordinate 174.070 -start_high_ends coordinate  -start_high_ends_coordinate 1226.940 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal5 straps for net VDD
create_power_straps  -direction horizontal  -start_at 217.000 -nets VDD  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 259.000 -nets VDD  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 301.000 -nets VDD  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 343.000 -nets VDD  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 385.000 -nets VDD  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 427.000 -nets VDD  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 469.000 -nets VDD  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 511.000 -nets VDD  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 553.000 -nets VDD  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 595.000 -nets VDD  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 637.000 -nets VDD  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 679.000 -nets VDD  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 720.600 -nets VDD  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 762.600 -nets VDD  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 804.600 -nets VDD  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 846.600 -nets VDD  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 888.600 -nets VDD  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 930.600 -nets VDD  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 972.600 -nets VDD  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1014.600 -nets VDD  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1056.600 -nets VDD  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1098.600 -nets VDD  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1140.600 -nets VDD  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1182.600 -nets VDD  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal5 straps for net VSS
create_power_straps  -direction horizontal  -start_at 218.240 -nets VSS  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 170.550 -start_high_ends coordinate  -start_high_ends_coordinate 1229.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 260.240 -nets VSS  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 170.550 -start_high_ends coordinate  -start_high_ends_coordinate 1229.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 302.240 -nets VSS  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 170.550 -start_high_ends coordinate  -start_high_ends_coordinate 1229.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 344.240 -nets VSS  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 170.550 -start_high_ends coordinate  -start_high_ends_coordinate 1229.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 386.240 -nets VSS  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 170.550 -start_high_ends coordinate  -start_high_ends_coordinate 1229.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 428.240 -nets VSS  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 170.550 -start_high_ends coordinate  -start_high_ends_coordinate 1229.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 470.240 -nets VSS  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 170.550 -start_high_ends coordinate  -start_high_ends_coordinate 1229.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 512.240 -nets VSS  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 170.550 -start_high_ends coordinate  -start_high_ends_coordinate 1229.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 554.240 -nets VSS  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 170.550 -start_high_ends coordinate  -start_high_ends_coordinate 1229.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 596.240 -nets VSS  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 170.550 -start_high_ends coordinate  -start_high_ends_coordinate 1229.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 638.240 -nets VSS  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 170.550 -start_high_ends coordinate  -start_high_ends_coordinate 1229.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 680.240 -nets VSS  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 170.550 -start_high_ends coordinate  -start_high_ends_coordinate 1229.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 721.840 -nets VSS  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 170.550 -start_high_ends coordinate  -start_high_ends_coordinate 1229.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 763.840 -nets VSS  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 170.550 -start_high_ends coordinate  -start_high_ends_coordinate 1229.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 805.840 -nets VSS  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 170.550 -start_high_ends coordinate  -start_high_ends_coordinate 1229.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 847.840 -nets VSS  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 170.550 -start_high_ends coordinate  -start_high_ends_coordinate 1229.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 889.840 -nets VSS  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 170.550 -start_high_ends coordinate  -start_high_ends_coordinate 1229.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 931.840 -nets VSS  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 170.550 -start_high_ends coordinate  -start_high_ends_coordinate 1229.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 973.840 -nets VSS  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 170.550 -start_high_ends coordinate  -start_high_ends_coordinate 1229.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1015.840 -nets VSS  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 170.550 -start_high_ends coordinate  -start_high_ends_coordinate 1229.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1057.840 -nets VSS  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 170.550 -start_high_ends coordinate  -start_high_ends_coordinate 1229.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1099.840 -nets VSS  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 170.550 -start_high_ends coordinate  -start_high_ends_coordinate 1229.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1141.840 -nets VSS  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 170.550 -start_high_ends coordinate  -start_high_ends_coordinate 1229.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1183.840 -nets VSS  -layer MET5 -width 0.910 -pitch_within_group 41.990 -start_low_ends coordinate  -start_low_ends_coordinate 170.550 -start_high_ends coordinate  -start_high_ends_coordinate 1229.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal6 straps for net VDD
create_power_straps  -direction vertical  -start_at 213.500 -nets VDD  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 255.740 -nets VDD  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 297.980 -nets VDD  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 340.220 -nets VDD  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 382.460 -nets VDD  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 424.700 -nets VDD  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 466.940 -nets VDD  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 509.180 -nets VDD  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 551.420 -nets VDD  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 593.660 -nets VDD  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 635.900 -nets VDD  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 678.140 -nets VDD  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 720.380 -nets VDD  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 762.620 -nets VDD  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 804.860 -nets VDD  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 847.100 -nets VDD  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 889.340 -nets VDD  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 931.580 -nets VDD  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 973.820 -nets VDD  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1016.060 -nets VDD  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1058.300 -nets VDD  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1100.540 -nets VDD  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1142.780 -nets VDD  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1185.020 -nets VDD  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal6 straps for net VSS
create_power_straps  -direction vertical  -start_at 214.980 -nets VSS  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 174.070 -start_high_ends coordinate  -start_high_ends_coordinate 1226.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 257.220 -nets VSS  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 174.070 -start_high_ends coordinate  -start_high_ends_coordinate 1226.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 299.460 -nets VSS  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 174.070 -start_high_ends coordinate  -start_high_ends_coordinate 1226.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 341.700 -nets VSS  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 174.070 -start_high_ends coordinate  -start_high_ends_coordinate 1226.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 383.940 -nets VSS  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 174.070 -start_high_ends coordinate  -start_high_ends_coordinate 1226.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 426.180 -nets VSS  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 174.070 -start_high_ends coordinate  -start_high_ends_coordinate 1226.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 468.420 -nets VSS  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 174.070 -start_high_ends coordinate  -start_high_ends_coordinate 1226.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 510.660 -nets VSS  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 174.070 -start_high_ends coordinate  -start_high_ends_coordinate 1226.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 552.900 -nets VSS  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 174.070 -start_high_ends coordinate  -start_high_ends_coordinate 1226.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 595.140 -nets VSS  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 174.070 -start_high_ends coordinate  -start_high_ends_coordinate 1226.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 637.380 -nets VSS  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 174.070 -start_high_ends coordinate  -start_high_ends_coordinate 1226.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 679.620 -nets VSS  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 174.070 -start_high_ends coordinate  -start_high_ends_coordinate 1226.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 721.860 -nets VSS  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 174.070 -start_high_ends coordinate  -start_high_ends_coordinate 1226.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 764.100 -nets VSS  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 174.070 -start_high_ends coordinate  -start_high_ends_coordinate 1226.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 806.340 -nets VSS  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 174.070 -start_high_ends coordinate  -start_high_ends_coordinate 1226.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 848.580 -nets VSS  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 174.070 -start_high_ends coordinate  -start_high_ends_coordinate 1226.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 890.820 -nets VSS  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 174.070 -start_high_ends coordinate  -start_high_ends_coordinate 1226.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 933.060 -nets VSS  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 174.070 -start_high_ends coordinate  -start_high_ends_coordinate 1226.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 975.300 -nets VSS  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 174.070 -start_high_ends coordinate  -start_high_ends_coordinate 1226.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1017.540 -nets VSS  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 174.070 -start_high_ends coordinate  -start_high_ends_coordinate 1226.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1059.780 -nets VSS  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 174.070 -start_high_ends coordinate  -start_high_ends_coordinate 1226.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1102.020 -nets VSS  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 174.070 -start_high_ends coordinate  -start_high_ends_coordinate 1226.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1144.260 -nets VSS  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 174.070 -start_high_ends coordinate  -start_high_ends_coordinate 1226.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1186.500 -nets VSS  -layer MET6 -width 0.910 -pitch_within_group 42.230 -start_low_ends coordinate  -start_low_ends_coordinate 174.070 -start_high_ends coordinate  -start_high_ends_coordinate 1226.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
