make -f Makefile_sys 00_read_design
make -f Makefile_sys 01_floorplan
make -f Makefile_sys 02_powerplan
make -f Makefile_sys 03_place_opt
make -f Makefile_sys 04_clock_opt_cts
make -f Makefile_sys 05_clock_opt_post_cts
make -f Makefile_sys 06_route
make -f Makefile_sys 07_route_opt
make -f Makefile_sys 08_chip_finish
